export const packageName = "@acos/contracts" as const;

export {
  ERROR_CODES,
  ProblemJsonSchema,
  PROBLEM_TYPE_BASE,
  problemFor,
  type ErrorCode,
  type ProblemJson,
} from "./errors.js";
export {
  HealthResponseSchema,
  DependencyStatusSchema,
  type HealthResponse,
  type DependencyStatus,
} from "./health.js";
export {
  SessionUserSchema,
  SetupStatusSchema,
  SetupRequestSchema,
  LoginRequestSchema,
  LoginResponseSchema,
  TotpRequiredResponseSchema,
  PatCreateRequestSchema,
  PatCreatedSchema,
  PatListItemSchema,
  TotpEnableRequestSchema,
  TotpEnableResponseSchema,
  TotpConfirmRequestSchema,
  TotpDisableRequestSchema,
  OkSchema,
  type SessionUser,
} from "./auth.js";
export {
  CompanySchema,
  CreateCompanyRequestSchema,
  CompanySettingsSchema,
  UpdateCompanySettingsRequestSchema,
  type Company,
  type CompanySettings,
} from "./companies.js";
export {
  UnitKindSchema,
  EdgeKindSchema,
  OrgUnitSchema,
  CreateOrgUnitRequestSchema,
  MoveOrgUnitRequestSchema,
  PositionSchema,
  CreatePositionRequestSchema,
  OrgEdgeSchema,
  CreateOrgEdgeRequestSchema,
  EscalationChainSchema,
  TeamRosterEntrySchema,
  type OrgUnit,
  type Position,
  type OrgEdge,
  type EscalationChain,
} from "./org.js";
export {
  EventActorSchema,
  EventSchema,
  EventListQuerySchema,
  EventListResponseSchema,
  EventReplayQuerySchema,
  EventReplayResponseSchema,
  type Event,
  type EventListResponse,
  type EventReplayResponse,
} from "./events.js";
export {
  parseTopic,
  ClientOpSchema,
  SubscribeOpSchema,
  ResumeOpSchema,
  UnsubscribeOpSchema,
  PingOpSchema,
  HelloFrameSchema,
  SubOkFrameSchema,
  ReplayDoneFrameSchema,
  EventsDataFrameSchema,
  TerminalFrameSchema,
  TerminalDataFrameSchema,
  PresenceSnapshotFrameSchema,
  GapFrameSchema,
  PongFrameSchema,
  ErrorFrameSchema,
  ServerControlFrameSchema,
  WS_ERROR_CODES,
  WS_CLOSE_CODES,
  type TopicKind,
  type ParsedTopic,
  type ClientOp,
  type ServerControlFrame,
  type EventsDataFrame,
} from "./realtime.js";
export {
  ChannelKindSchema,
  ChannelSchema,
  MessageKindSchema,
  MessageSchema,
  SendMessageRequestSchema,
  CreateDmRequestSchema,
  ChannelMemberSchema,
  type Channel,
  type Message,
} from "./comms.js";
export {
  TASK_NEXT_STATUSES,
  TaskKindSchema,
  TaskPrioritySchema,
  TaskStatusSchema,
  TaskRiskLevelSchema,
  TaskSchema,
  CreateTaskRequestSchema,
  UpdateTaskRequestSchema,
  TaskTransitionRequestSchema,
  TaskListQuerySchema,
  CreateDependencyRequestSchema,
  TaskDependencySchema,
  TaskDependenciesResponseSchema,
  CreateAssignmentRequestSchema,
  TaskAssignmentSchema,
  TaskTreeNodeSchema,
  type Task,
  type TaskAssignment,
  type TaskDependency,
  type TaskTreeNode,
} from "./tasks.js";
export {
  CellSchema,
  OfficeDeskSchema,
  OfficeZoneSchema,
  OfficeLayoutSchema,
  PRESENCE_BADGES,
  PresenceBadgeSchema,
  AvatarMovedSchema,
  InteractionStartedSchema,
  InteractionEndedSchema,
  StatusChangedSchema,
  OfficeInstructionSchema,
  PresenceAgentSchema,
  PresenceStateSchema,
  type Cell,
  type OfficeLayout,
  type OfficeZone,
  type OfficeDesk,
  type PresenceBadge,
  type OfficeInstruction,
  type PresenceState,
  type PresenceAgent,
} from "./office.js";
export {
  RealtimeClient,
  type CursorStore,
  type WebSocketLike,
  type RealtimeStatus,
  type FrameMeta,
  type FrameHandler,
  type RealtimeClientOptions,
} from "./realtime-client.js";
export {
  IsolationLevelSchema,
  WorkspaceMountSchema,
  CreateWorkspaceRequestSchema,
  WorkspaceSchema,
  ExecRequestSchema,
  ExecResultSchema,
  ExecStreamAckSchema,
  TerminalFrameSchema as SandboxTerminalFrameSchema,
  WorkspaceListSchema,
  TASK_BRANCH_PATTERN,
  WORKTREE_VOLUME_PATTERN,
  EnsureRepoRequestSchema,
  EnsureRepoResponseSchema,
  ProvisionWorktreeRequestSchema,
  ProvisionWorktreeResponseSchema,
  type CreateWorkspaceRequest,
  type Workspace,
  type ExecRequest,
  type ExecResult,
  type SandboxTerminalFrame,
  type EnsureRepoRequest,
  type EnsureRepoResponse,
  type ProvisionWorktreeRequest,
  type ProvisionWorktreeResponse,
} from "./sandbox.js";
export {
  ApprovalBriefSchema,
  ApprovalKindSchema,
  ApprovalStatusSchema,
  ApprovalUrgencySchema,
  ApprovalRiskSchema,
  ApprovalChainEntrySchema,
  ApprovalSchema,
  ApprovalDetailSchema,
  ApprovalListQuerySchema,
  ApprovalVerdictRequestSchema,
  type ApprovalBrief,
  type Approval,
  type ApprovalDetail,
  type ApprovalVerdictRequest,
} from "./approvals.js";
export {
  AgentSchema,
  AgentStatusSchema,
  SenioritySchema,
  BindingPurposeSchema,
  HireAgentRequestSchema,
  UpdateAgentRequestSchema,
  LifecycleActionRequestSchema,
  ModelBindingSchema,
  SetModelBindingRequestSchema,
  AgentSessionSchema,
  type Agent,
  type ModelBinding,
} from "./agents.js";
